// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvuS30Ez0TV27sA0WX066BO5yBYkNOXqo',
    appId: '1:921079372710:web:9b6223403f852c9984cd67',
    messagingSenderId: '921079372710',
    projectId: 'yeniasya-d401b',
    authDomain: 'yeniasya-d401b.firebaseapp.com',
    storageBucket: 'yeniasya-d401b.firebasestorage.app',
    measurementId: 'G-3PB21DXFRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPMItz3SCtm3jSJhOxoGScz7xh8CWlh_k',
    appId: '1:921079372710:android:2aaf656bd83b7bec84cd67',
    messagingSenderId: '921079372710',
    projectId: 'yeniasya-d401b',
    storageBucket: 'yeniasya-d401b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5MVk4qIcYQrnc1jLsnNFRYiRe3Q_7xrY',
    appId: '1:921079372710:ios:99bb544b24e5961684cd67',
    messagingSenderId: '921079372710',
    projectId: 'yeniasya-d401b',
    storageBucket: 'yeniasya-d401b.firebasestorage.app',
    androidClientId: '921079372710-g24ul48s7s83obst2861vmsgogbg5arp.apps.googleusercontent.com',
    iosClientId: '921079372710-8npk6tcfr5b4e4jvsr69ckik4kma309d.apps.googleusercontent.com',
    iosBundleId: 'com.yeniasya.books',
  );
}
